version: '3.7'

services:
  db:
    image: postgres:9
    environment:
      POSTGRES_DB: "wallet"
      POSTGRES_PASSWORD: "postgres"
    ports:
      - "15432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge